gen_file:
  age -a -r age1q2adsrv2cz09uh4fs3u40kj5pq9nqh6gskumfmlavp4amzu6ydxqwuueye i_am_groot.txt > i_am_groot_armored.txt.age
  age -r age1q2adsrv2cz09uh4fs3u40kj5pq9nqh6gskumfmlavp4amzu6ydxqwuueye i_am_groot.txt > i_am_groot.txt.age
