name: Test Plugin
on:
  push:
  #  paths:
  #    - 'src/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Run Age genkey test
        run: |
          nvim --headless -h
          ls 